services: 
  backend-hackathon:
    image: python:3.9
    ports:
      - "8000:8000"
    working_dir: /app
    command: bash -c "pip install --upgrade pip && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend:/app